[package]
name = "write-to-a-windows-event-log"
version = "0.1.0"
edition = "2018"

[package.metadata.rosettacode]
url = "http://rosettacode.org/wiki/Write_to_Windows_event_log"

[target.'cfg(windows)'.dependencies]
windows = "0.38.0"

[target.'cfg(windows)'.build-dependencies]
windows = "0.38.0"